[package]
name = "yy-boss"
version = "0.1.0"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"

[dependencies]
yy-typings = { path = "../yy-typings" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

anyhow = "1"
log = "0.4"
image = "0.23"
regex = "1.3"
strum = "0.18"
strum_macros = "0.18"
thiserror = "1"
maplit = "1"
console = "0.11.3"

[dev-dependencies]
include_dir = { version = "0.6", features = ["search"]}
