name: Rust

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
        if: startsWith(github.ref, 'refs/tags/')

      - name: Compress
        shell: powershell
        run: Compress-Archive target/release/mistria-manager.exe -DestinationPath "Mistria Manager.zip"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Mistria Manager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/mistria-manager && mv target/release/mistria-manager target/release/mistria-manager_darwin
        if: startsWith(github.ref, 'refs/tags/')

      - name: Compress
        run: zip "Mistria Manager Darwin.zip" target/release/mistria-manager_darwin
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Mistria Manager Darwin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
